//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjEShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public int CouponId { get; set; }
        public string CouponNumber { get; set; }
        public string CouponName { get; set; }
        public string CouponDetails { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string CouponTerms { get; set; }
        public string CouponType { get; set; }
        public string Discount { get; set; }
        public string Storewide { get; set; }
        public string StartTime { get; set; }
        public string ClaimDeadline { get; set; }
        public string EndTime { get; set; }
        public string EventStatus { get; set; }
    }
}
