//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjEShopping.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EShoppingEntities : DbContext
    {
        public EShoppingEntities()
            : base("name=EShoppingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessRight> AccessRights { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<ADPoint> ADPoints { get; set; }
        public virtual DbSet<ADProduct> ADProducts { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<FlashSaleAD> FlashSaleADs { get; set; }
        public virtual DbSet<FullPageAD> FullPageADs { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<ProductDetail> ProductDetails { get; set; }
        public virtual DbSet<ProductInventory> ProductInventories { get; set; }
        public virtual DbSet<ProductMainCategory> ProductMainCategories { get; set; }
        public virtual DbSet<ProductOption> ProductOptions { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductSpecification> ProductSpecifications { get; set; }
        public virtual DbSet<ProductStatusDetail> ProductStatusDetails { get; set; }
        public virtual DbSet<ProductStock> ProductStocks { get; set; }
        public virtual DbSet<ProductSubCategory> ProductSubCategories { get; set; }
        public virtual DbSet<RatingReplay> RatingReplaies { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Seller> Sellers { get; set; }
        public virtual DbSet<ShipmentDetail> ShipmentDetails { get; set; }
        public virtual DbSet<Shipment> Shipments { get; set; }
        public virtual DbSet<ShipmentStatusDetail> ShipmentStatusDetails { get; set; }
        public virtual DbSet<ShippingMethod> ShippingMethods { get; set; }
        public virtual DbSet<ShoppingCartDetail> ShoppingCartDetails { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCarts { get; set; }
        public virtual DbSet<SliderAD> SliderADs { get; set; }
        public virtual DbSet<SupportReplay> SupportReplaies { get; set; }
        public virtual DbSet<Support> Supports { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersCoupon> UsersCoupons { get; set; }
    }
}
