//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjEShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public int SellerId { get; set; }
        public string SellerName { get; set; }
        public string StoreName { get; set; }
        public string SellerAccount { get; set; }
        public string SellerPassword { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string GUINumber { get; set; }
        public string StoreIntro { get; set; }
        public Nullable<int> AccessRightId { get; set; }
        public string BankAccount { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<int> ShippingMethodId { get; set; }
        public Nullable<int> ADPoints { get; set; }
        public string SellerImagePath { get; set; }
    }
}
