//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjEShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int ShipmentId { get; set; }
        public string ShipmentNumber { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> SellerId { get; set; }
        public string ShipmentDate { get; set; }
        public string ShipDate { get; set; }
        public string ArrivalTimeDate { get; set; }
        public string CompletionDate { get; set; }
        public string PickDate { get; set; }
        public Nullable<int> ShipmentStatusId { get; set; }
    }
}
