//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjEShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentDetail
    {
        public int ShipmentDetailId { get; set; }
        public string ShipmentNumber { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<int> ShippingMethodId { get; set; }
        public string Receiver { get; set; }
        public string ReceiverAddress { get; set; }
    }
}
