//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjEShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportReplay
    {
        public int SupportReplayId { get; set; }
        public Nullable<int> SupportId { get; set; }
        public Nullable<int> AdminId { get; set; }
        public string ReplayTitle { get; set; }
        public string ReplayText { get; set; }
        public string ReplayTime { get; set; }
        public string SupportReplayStatus { get; set; }
    }
}
