//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjEShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserAccount { get; set; }
        public string UserPassword { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string CellPhone { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string ShippingMethodId { get; set; }
        public string PaymenyMethodId { get; set; }
        public string Birthday { get; set; }
        public string AccessRightId { get; set; }
        public string UserImagePath { get; set; }
    }
}
